import React, { useRef, useEffect } from 'react';
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  TouchableOpacity,
  Animated,
} from 'react-native';
import { Stack, useRouter } from 'expo-router';
import { X, FileText, CheckCircle, AlertTriangle, CreditCard, Scale } from 'lucide-react-native';
import Colors from '@/constants/colors';
import { BRAND } from '@/constants/branding';

const LAST_UPDATED = 'March 14, 2026';

interface SectionProps {
  number: string;
  title: string;
  children: React.ReactNode;
}

function TermsSection({ number, title, children }: SectionProps) {
  return (
    <View style={styles.section}>
      <View style={styles.sectionHeader}>
        <View style={styles.numberBadge}>
          <Text style={styles.numberText}>{number}</Text>
        </View>
        <Text style={styles.sectionTitle}>{title}</Text>
      </View>
      <View style={styles.sectionBody}>{children}</View>
    </View>
  );
}

export default function TermsOfServiceScreen() {
  const router = useRouter();
  const fadeAnim = useRef(new Animated.Value(0)).current;

  useEffect(() => {
    Animated.timing(fadeAnim, {
      toValue: 1,
      duration: 500,
      useNativeDriver: true,
    }).start();
  }, [fadeAnim]);

  return (
    <View style={styles.container}>
      <Stack.Screen options={{ headerShown: false }} />

      <View style={styles.header}>
        <TouchableOpacity
          style={styles.closeBtn}
          onPress={() => router.back()}
          hitSlop={{ top: 12, bottom: 12, left: 12, right: 12 }}
          testID="close-btn"
        >
          <X size={20} color={Colors.textSecondary} />
        </TouchableOpacity>
        <Text style={styles.headerTitle}>Terms of Service</Text>
        <View style={styles.closeBtn} />
      </View>

      <ScrollView
        style={styles.scroll}
        contentContainerStyle={styles.scrollContent}
        showsVerticalScrollIndicator={false}
      >
        <Animated.View style={[styles.heroCard, { opacity: fadeAnim }]}>
          <View style={styles.heroIconWrap}>
            <FileText size={28} color={Colors.brandNavy} />
          </View>
          <Text style={styles.heroTitle}>Terms of Service</Text>
          <Text style={styles.heroDesc}>
            Please read these terms carefully. By using {BRAND.name}, you agree to be bound by these terms.
          </Text>
          <View style={styles.updatedBadge}>
            <Text style={styles.updatedText}>Effective: {LAST_UPDATED}</Text>
          </View>
        </Animated.View>

        <TermsSection number="1" title="Acceptance of Terms">
          <Text style={styles.bodyText}>
            By downloading, installing, or using {BRAND.name} ("the App"), you agree to these Terms of Service. If you do not agree to these terms, please do not use the App.
          </Text>
          <Text style={styles.bodyText}>
            You must be at least 16 years of age to use this App. If you are under 18, you should have a parent or guardian review these terms with you.
          </Text>
        </TermsSection>

        <TermsSection number="2" title="Nature of the App">
          <View style={styles.warningCard}>
            <AlertTriangle size={16} color={Colors.accent} />
            <Text style={styles.warningText}>
              {BRAND.name} is a self-help companion tool. It is NOT a substitute for professional mental health treatment, therapy, or medical advice.
            </Text>
          </View>
          <Text style={styles.bodyText}>
            The App provides tools for emotional awareness, journaling, communication support, and self-reflection. Content generated by AI features is for informational and reflective purposes only.
          </Text>
          <Text style={styles.bodyText}>
            If you are in crisis or experiencing a mental health emergency, please contact emergency services (911) or the 988 Suicide & Crisis Lifeline immediately.
          </Text>
        </TermsSection>

        <TermsSection number="3" title="User Accounts & Data">
          <Text style={styles.bodyText}>
            You are responsible for maintaining the confidentiality of your account. All data you enter into the App (journal entries, messages, check-ins) is your personal data.
          </Text>
          <View style={styles.bulletList}>
            <Text style={styles.bulletItem}>You retain ownership of your content</Text>
            <Text style={styles.bulletItem}>We store data as described in our Privacy Policy</Text>
            <Text style={styles.bulletItem}>You may request data deletion at any time</Text>
            <Text style={styles.bulletItem}>We will not share your personal data with third parties for advertising</Text>
          </View>
        </TermsSection>

        <TermsSection number="4" title="Subscriptions & Payments">
          <View style={styles.iconRow}>
            <CreditCard size={16} color={Colors.brandTeal} />
            <Text style={styles.iconRowText}>In-App Purchases</Text>
          </View>
          <Text style={styles.bodyText}>
            Some features require a premium subscription. Subscriptions are billed through your App Store or Google Play account.
          </Text>
          <View style={styles.bulletList}>
            <Text style={styles.bulletItem}>Subscriptions auto-renew unless cancelled at least 24 hours before the end of the current period</Text>
            <Text style={styles.bulletItem}>You can manage subscriptions in your device settings</Text>
            <Text style={styles.bulletItem}>Refunds are handled by Apple/Google per their policies</Text>
            <Text style={styles.bulletItem}>Free features including crisis support remain always accessible</Text>
          </View>
        </TermsSection>

        <TermsSection number="5" title="Acceptable Use">
          <Text style={styles.bodyText}>
            You agree not to:
          </Text>
          <View style={styles.bulletList}>
            <Text style={styles.bulletItem}>Use the App to harm, threaten, or harass others</Text>
            <Text style={styles.bulletItem}>Post harmful, abusive, or illegal content in community features</Text>
            <Text style={styles.bulletItem}>Attempt to reverse-engineer or exploit the App</Text>
            <Text style={styles.bulletItem}>Use AI features to generate harmful content</Text>
            <Text style={styles.bulletItem}>Share your account credentials with others</Text>
          </View>
        </TermsSection>

        <TermsSection number="6" title="Community Guidelines">
          <Text style={styles.bodyText}>
            Community features are designed for peer support. All community interactions must be respectful, supportive, and constructive.
          </Text>
          <Text style={styles.bodyText}>
            We reserve the right to remove content or suspend accounts that violate these guidelines.
          </Text>
        </TermsSection>

        <TermsSection number="7" title="Limitation of Liability">
          <View style={styles.iconRow}>
            <Scale size={16} color="#8B5CF6" />
            <Text style={styles.iconRowText}>Legal Disclaimer</Text>
          </View>
          <Text style={styles.bodyText}>
            The App is provided "as is" without warranties of any kind. We are not liable for any decisions made based on App content, AI-generated suggestions, or community interactions.
          </Text>
          <Text style={styles.bodyText}>
            To the maximum extent permitted by law, we shall not be liable for any indirect, incidental, or consequential damages arising from your use of the App.
          </Text>
        </TermsSection>

        <TermsSection number="8" title="Changes to Terms">
          <Text style={styles.bodyText}>
            We may update these terms from time to time. Continued use of the App after changes constitutes acceptance of the updated terms. We will notify you of significant changes through the App.
          </Text>
        </TermsSection>

        <TermsSection number="9" title="Contact">
          <Text style={styles.bodyText}>
            For questions about these terms:
          </Text>
          <View style={styles.contactCard}>
            <Text style={styles.contactLabel}>Email</Text>
            <Text style={styles.contactValue}>legal@bpdcompanion.app</Text>
          </View>
        </TermsSection>

        <View style={styles.acceptanceCard}>
          <CheckCircle size={18} color={Colors.success} />
          <Text style={styles.acceptanceText}>
            By using {BRAND.name}, you acknowledge that you have read, understood, and agree to these Terms of Service.
          </Text>
        </View>

        <View style={styles.bottomSpacer} />
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.background,
  },
  header: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    justifyContent: 'space-between' as const,
    paddingHorizontal: 20,
    paddingTop: 56,
    paddingBottom: 16,
    backgroundColor: Colors.background,
  },
  closeBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: Colors.surface,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
  },
  headerTitle: {
    fontSize: 17,
    fontWeight: '600' as const,
    color: Colors.brandNavy,
    letterSpacing: -0.2,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingBottom: 40,
  },
  heroCard: {
    backgroundColor: Colors.surface,
    borderRadius: 20,
    padding: 24,
    alignItems: 'center' as const,
    marginBottom: 24,
  },
  heroIconWrap: {
    width: 56,
    height: 56,
    borderRadius: 16,
    backgroundColor: Colors.white,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    marginBottom: 16,
    shadowColor: 'rgba(27,40,56,0.08)',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 1,
    shadowRadius: 12,
    elevation: 3,
  },
  heroTitle: {
    fontSize: 22,
    fontWeight: '700' as const,
    color: Colors.brandNavy,
    letterSpacing: -0.3,
    marginBottom: 10,
  },
  heroDesc: {
    fontSize: 14,
    color: Colors.textSecondary,
    lineHeight: 21,
    textAlign: 'center' as const,
  },
  updatedBadge: {
    marginTop: 16,
    paddingHorizontal: 14,
    paddingVertical: 6,
    borderRadius: 20,
    backgroundColor: Colors.white,
  },
  updatedText: {
    fontSize: 12,
    fontWeight: '500' as const,
    color: Colors.textMuted,
  },
  section: {
    backgroundColor: Colors.card,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: Colors.borderLight,
    marginBottom: 14,
    overflow: 'hidden' as const,
    shadowColor: 'rgba(27,40,56,0.04)',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 1,
    shadowRadius: 8,
    elevation: 1,
  },
  sectionHeader: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    padding: 16,
    paddingBottom: 0,
    gap: 10,
  },
  numberBadge: {
    width: 28,
    height: 28,
    borderRadius: 8,
    backgroundColor: Colors.brandNavy,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
  },
  numberText: {
    fontSize: 13,
    fontWeight: '700' as const,
    color: Colors.white,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '600' as const,
    color: Colors.brandNavy,
    flex: 1,
  },
  sectionBody: {
    padding: 16,
    paddingTop: 12,
  },
  bodyText: {
    fontSize: 14,
    color: Colors.textSecondary,
    lineHeight: 21,
    marginBottom: 10,
  },
  bulletList: {
    marginBottom: 10,
    gap: 6,
  },
  bulletItem: {
    fontSize: 14,
    color: Colors.text,
    lineHeight: 20,
    paddingLeft: 16,
  },
  warningCard: {
    flexDirection: 'row' as const,
    gap: 10,
    backgroundColor: Colors.accentLight,
    borderRadius: 12,
    padding: 14,
    marginBottom: 12,
    alignItems: 'flex-start' as const,
  },
  warningText: {
    flex: 1,
    fontSize: 13,
    fontWeight: '500' as const,
    color: Colors.text,
    lineHeight: 19,
  },
  iconRow: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 8,
    marginBottom: 10,
  },
  iconRowText: {
    fontSize: 13,
    fontWeight: '600' as const,
    color: Colors.textSecondary,
  },
  contactCard: {
    backgroundColor: Colors.surface,
    borderRadius: 12,
    padding: 14,
    marginVertical: 8,
  },
  contactLabel: {
    fontSize: 11,
    fontWeight: '600' as const,
    color: Colors.textMuted,
    textTransform: 'uppercase' as const,
    letterSpacing: 0.5,
    marginBottom: 4,
  },
  contactValue: {
    fontSize: 15,
    fontWeight: '600' as const,
    color: Colors.brandTeal,
  },
  acceptanceCard: {
    flexDirection: 'row' as const,
    alignItems: 'flex-start' as const,
    gap: 12,
    backgroundColor: Colors.successLight,
    borderRadius: 14,
    padding: 16,
    marginTop: 10,
  },
  acceptanceText: {
    flex: 1,
    fontSize: 13,
    color: Colors.text,
    lineHeight: 19,
  },
  bottomSpacer: {
    height: 30,
  },
});
